[2025-10-11T14:12:17.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T14:12:17.742+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_routes.truncate_table_routes manual__2025-10-11T14:12:04.946871+00:00 [queued]>
[2025-10-11T14:12:17.761+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_routes.truncate_table_routes manual__2025-10-11T14:12:04.946871+00:00 [queued]>
[2025-10-11T14:12:17.765+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T14:12:17.794+0000] {taskinstance.py:2327} INFO - Executing <Task(MariaDBOperator): group_routes.truncate_table_routes> on 2025-10-11 14:12:04.946871+00:00
[2025-10-11T14:12:17.808+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T14:12:17.814+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2025-10-11T14:12:17.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_routes.truncate_table_routes', 'manual__2025-10-11T14:12:04.946871+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmp0k_kez5y']
[2025-10-11T14:12:17.818+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask group_routes.truncate_table_routes
[2025-10-11T14:12:17.931+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_routes.truncate_table_routes manual__2025-10-11T14:12:04.946871+00:00 [running]> on host 74db4dd39b04
[2025-10-11T14:12:18.101+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_routes.truncate_table_routes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T14:12:04.946871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T14:12:04.946871+00:00'
[2025-10-11T14:12:18.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T14:12:18.105+0000] {sql.py:276} INFO - Executing: 
                Truncate table open_flights_data.routes
                
[2025-10-11T14:12:18.119+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T14:12:18.134+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `maria_db_default` isn't defined
[2025-10-11T14:12:18.144+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_routes.truncate_table_routes, execution_date=20251011T141204, start_date=20251011T141217, end_date=20251011T141218
[2025-10-11T14:12:18.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task group_routes.truncate_table_routes (The conn_id `maria_db_default` isn't defined; 86)
[2025-10-11T14:12:18.205+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T14:12:18.324+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MariaDBOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-10-11T14:12:18.356+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:12:18.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
