[2025-10-12T19:54:13.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-12T19:54:13.317+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_airports.drop_table_airports manual__2025-10-12T19:53:58.142590+00:00 [queued]>
[2025-10-12T19:54:13.366+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_airports.drop_table_airports manual__2025-10-12T19:53:58.142590+00:00 [queued]>
[2025-10-12T19:54:13.367+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-12T19:54:13.406+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_airports.drop_table_airports> on 2025-10-12 19:53:58.142590+00:00
[2025-10-12T19:54:13.424+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-12T19:54:13.437+0000] {standard_task_runner.py:63} INFO - Started process 77 to run task
[2025-10-12T19:54:13.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SFTP', 'group_airports.drop_table_airports', 'manual__2025-10-12T19:53:58.142590+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmp1ae_nthc']
[2025-10-12T19:54:13.447+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask group_airports.drop_table_airports
[2025-10-12T19:54:13.608+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SFTP.group_airports.drop_table_airports manual__2025-10-12T19:53:58.142590+00:00 [running]> on host 81d6fa278de1
[2025-10-12T19:54:13.801+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SFTP' AIRFLOW_CTX_TASK_ID='group_airports.drop_table_airports' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T19:53:58.142590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T19:53:58.142590+00:00'
[2025-10-12T19:54:13.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-12T19:54:13.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-12T19:54:13.856+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 28, in drop_table_if_exists
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 23, in get_conn
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `maria_db_default` isn't defined
[2025-10-12T19:54:13.868+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SFTP, task_id=group_airports.drop_table_airports, execution_date=20251012T195358, start_date=20251012T195413, end_date=20251012T195413
[2025-10-12T19:54:13.910+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task group_airports.drop_table_airports (The conn_id `maria_db_default` isn't defined; 77)
[2025-10-12T19:54:13.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-12T19:54:14.024+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T19:54:14.031+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
