[2025-10-11T19:14:48.102+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-11T19:14:48.136+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airport_extended.truncate_table_airport_extended manual__2025-10-11T19:14:35.648523+00:00 [queued]>
[2025-10-11T19:14:48.149+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion.group_airport_extended.truncate_table_airport_extended manual__2025-10-11T19:14:35.648523+00:00 [queued]>
[2025-10-11T19:14:48.150+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-11T19:14:48.169+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_airport_extended.truncate_table_airport_extended> on 2025-10-11 19:14:35.648523+00:00
[2025-10-11T19:14:48.178+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-11T19:14:48.183+0000] {standard_task_runner.py:63} INFO - Started process 82 to run task
[2025-10-11T19:14:48.183+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion', 'group_airport_extended.truncate_table_airport_extended', 'manual__2025-10-11T19:14:35.648523+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpq0yg2gy0']
[2025-10-11T19:14:48.186+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask group_airport_extended.truncate_table_airport_extended
[2025-10-11T19:14:48.265+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion.group_airport_extended.truncate_table_airport_extended manual__2025-10-11T19:14:35.648523+00:00 [running]> on host 187d1545c280
[2025-10-11T19:14:48.439+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion' AIRFLOW_CTX_TASK_ID='group_airport_extended.truncate_table_airport_extended' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T19:14:35.648523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T19:14:35.648523+00:00'
[2025-10-11T19:14:48.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-11T19:14:48.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-11T19:14:48.479+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 33, in truncate_if_exists
    result = hook.get_first(sql_check)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 276, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 23, in get_conn
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `maria_db_default` isn't defined
[2025-10-11T19:14:48.491+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion, task_id=group_airport_extended.truncate_table_airport_extended, execution_date=20251011T191435, start_date=20251011T191448, end_date=20251011T191448
[2025-10-11T19:14:48.515+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task group_airport_extended.truncate_table_airport_extended (The conn_id `maria_db_default` isn't defined; 82)
[2025-10-11T19:14:48.531+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-11T19:14:48.578+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T19:14:48.587+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
