[2025-10-12T20:03:48.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-12T20:03:48.823+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.drop_table_planes manual__2025-10-12T20:03:40.874784+00:00 [queued]>
[2025-10-12T20:03:48.842+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.drop_table_planes manual__2025-10-12T20:03:40.874784+00:00 [queued]>
[2025-10-12T20:03:48.843+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-10-12T20:03:48.878+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): group_planes.drop_table_planes> on 2025-10-12 20:03:40.874784+00:00
[2025-10-12T20:03:48.891+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-12T20:03:48.894+0000] {standard_task_runner.py:63} INFO - Started process 108 to run task
[2025-10-12T20:03:48.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'OpenFlightsDataIngestion_SFTP', 'group_planes.drop_table_planes', 'manual__2025-10-12T20:03:40.874784+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/openflights_dag.py', '--cfg-path', '/tmp/tmpj93cmkxd']
[2025-10-12T20:03:48.901+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask group_planes.drop_table_planes
[2025-10-12T20:03:48.989+0000] {task_command.py:426} INFO - Running <TaskInstance: OpenFlightsDataIngestion_SFTP.group_planes.drop_table_planes manual__2025-10-12T20:03:40.874784+00:00 [running]> on host 81d6fa278de1
[2025-10-12T20:03:49.226+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='OpenFlightsDataIngestion_SFTP' AIRFLOW_CTX_TASK_ID='group_planes.drop_table_planes' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T20:03:40.874784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T20:03:40.874784+00:00'
[2025-10-12T20:03:49.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-12T20:03:49.249+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-12T20:03:49.273+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openflights_dag.py", line 28, in drop_table_if_exists
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/.local/src/airflow-mariadb-provider/airflow_mariadb_provider/hooks/mariadb_hook.py", line 23, in get_conn
    conn = self.get_connection(getattr(self, self.conn_name_attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `maria_db_default` isn't defined
[2025-10-12T20:03:49.286+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=OpenFlightsDataIngestion_SFTP, task_id=group_planes.drop_table_planes, execution_date=20251012T200340, start_date=20251012T200348, end_date=20251012T200349
[2025-10-12T20:03:49.307+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task group_planes.drop_table_planes (The conn_id `maria_db_default` isn't defined; 108)
[2025-10-12T20:03:49.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-12T20:03:49.372+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T20:03:49.378+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
